### ISSUE TITLE
Administrationsprogramm

### ISSUE THREAD

**Issue by ottnorml** [simonsymhoven/Datenkommunikation#29]
Die an den AuditLog-Server übertragenen Nachrichten sollen jeweils in einem Datensatz in das persistente AuditLog geschrieben werden. 
Darüber hinaus ist ein Administrationsprogramm zu schreiben, welches das AuditLog ausliest und aufbereitete statistische Informationen (Anzahl Clients, Anzahl Datensätze je Typ, ...) zum Inhalt ausgibt.

**Comment by simonsymhoven** [comment]
@ottnorml Kannst du das etwas erläutern? Was genau soll am Ende raus kommen dabei, wie soll das aussehen und wie soll es funktionieren? Alle notwendigen Infos stehen doch im Logfile?

**Comment by ottnorml** [comment]
Ich habe aus der Aufgabenstellung zitiert, in der es am Ende der Teilaufgabe 2.3 heißt:

> Die an den AuditLog-Server übertragenen Nachrichten sollen jeweils in einem Datensatz in das persistente AuditLog geschrieben werden.
> Darüber hinaus ist ein Administrationsprogramm zu schreiben, welches das AuditLog ausliest und aufbereitete statistische Informationen (Anzahl Clients, Anzahl Datensätze je Typ, ...) zum Inhalt ausgibt.

**Comment by simonsymhoven** [comment]
Na hoppala, das habe ich total unterschlagen. Schon eine Idee wie wir das umsetzen können? FileChosser zum AuditLog, der dass danneinließt? 
Man könnte die Zeilen zählen, darüber bekommen wir die Anzahl der Pdus und alles andere müsste man über die Strings in den Nachrichten finden, ist aber eher unschön oder?

**Comment by ottnorml** [comment]
Ich würde das Log-File mit serialisierten PDUs füllen, so dass der Interpreter danach entscheiden kann, was er damit machen möchte. Und als Lösung für das Problem mit der Anzahl an PDUs pro Server-Verbindung würde ich vorschlagen, dass wir für jede neue Server-Verbindung in ein neues Log-File schreiben. Die Admin-GUI hat dann ein Auswahlfenster um das entsprechenden Log-File einzulesen.

**Comment by simonsymhoven** [comment]
Hast du damit schon begonnen? Sonst würde ich mal beginnen die GUI zu bauen, in der ein AuditLog geladen werden kann

**Comment by ottnorml** [comment]
Ich hab schon ne generalisierte GUI gebaut. Die muss ich noch commiten, was ich im Laufe des morgigen Tages machen werde. Da sollte dann auch der neue Unterbau aus #25 komplett sein.

**Comment by simonsymhoven** [comment]
Okay, schaue ich mir dann an. Habe für mich auch ma ne GUI gebaut, ist aber ja dann hinfällig. Schaue mir deins morgen an. Bin ne Woche krank geschrieben, wenn du Lust hast schrieb mir kurz zu deinem Commit was noch zu tun ist, dass erledige ich das :D

**Comment by simonsymhoven** [comment]
@ottnorml Habe begonnen die GUI zu bauen. Links ist eine TreeView in die alle LogFiles aus dem /out Verzeichnis geladen werden. Wird auf eine gedrückt wird ein Thread gestartet der einen Ladebalken anzeigt solange die Analyse zu dem File läuft.Der zweite Thread analysiert das File und füllt die Felder in der Anchor Pane rechts daneben. Warte auf deinen Remake vom AuditLogServer Unterbau und fange dann an die Analyse zu schreiben

**Comment by simonsymhoven** [comment]
![Screenshot 2019-12-15 at 19 54 20](https://user-images.githubusercontent.com/26878018/70867361-ed87f880-1f74-11ea-86ba-9822ac147940.png)

**Comment by simonsymhoven** [comment]
#33 schließt dieses Issue
