### ISSUE TITLE
Benchmarks and Artifacts

### ISSUE THREAD

**Issue by ottnorml** [simonsymhoven/Datenkommunikation#31]
die csv Dateien der Benchmark Tests sind ausgewertet und die entsprechenden Charts erstellt

**Comment by simonsymhoven** [comment]
Benchmark Test wurden durchgeführt und die Ergebnisse im Repo abgelegt.

**Comment by simonsymhoven** [comment]
Charts sind erstellt und im 2. Tabellenblatt des jeweiligen cdv Files gespeichert. Median und arithmetisches Mittel der RTT über die 10 -50 Threads als Graph erstellt.
